values: 
  num_sim: 100
  grid_size: 32
  n_cell: 500
  mutation_rate: 0.001
  regeneration_days: 10
  mean_death: 20.0
  std_death: 5.0
  mean_sex: 0.5
  std_sex: 0.1
  mean_strength: 100.0
  std_strength: 20.0
  mean_velocity: 1.0
  std_velocity: 0.3

exp: 
  num_sim: 'Number of simulations (days) that will occur in total.'
  grid_size: 'Size of the square grid of the enviroment.'
  n_cell: 'Number of cells at the beginning of the simulation.'
  mutation_rate: 'Probability that the genome will be modified.'
  regeneration_days: 'Frequency (in days) at which the cells reproduce.'
  mean_death: 'Mean death age (one unit of age is one simulation days).'
  std_death: 'Standard deviation of age.'
  mean_sex: 'Probability to have a male.'
  std_sex: 'Standard deviation of sex attribution (the probability is gaussian with ).'
  mean_strength: 'Mean strength of a cell.'
  std_strength: 'Standard deviation of strength.'
  mean_velocity: 'Mean velocity of the cell. This represents the number of pixels the cell will move if it has a moving signal.'
  std_velocity: 'Standard deviaiton of the velocity of the cells.'